SECTION_NAMES = {
    "Item 1.": "Business",
    "Item 1A.": "Risk Factors",
    "Item 1B.": "Unresolved Staff Comments",
    "Item 1C.": "Cybersecurity",
    "Item 2.": "Properties",
    "Item 3.": "Legal Proceedings",
    "Item 4.": "Mine Safety Disclosures",
    "Item 5.": "Market for Registrant's Common Equity",
    "Item 6.": "Selected Financial Data",
    "Item 7.": "Management Discussion and Analysis",
    "Item 7A.": "Market Risk",
    "Item 8.": "Financial Statements",
    "Item 9.": "Changes in Accountants",
    "Item 9A.": "Controls and Procedures",
    "Item 9B.": "Other Information",
    "Item 9C.": "Foreign Jurisdictions",
    "Item 10.": "Directors and Executive Officers",
    "Item 11.": "Executive Compensation",
    "Item 12.": "Security Ownership",
    "Item 13.": "Related Party Transactions",
    "Item 14.": "Principal Accounting Fees",
    "Item 15.": "Exhibits",
    "Item 16.": "Form 10-K Summary",
}